name: car_shop_ms
description: "A new Flutter project."

# Prevent accidental publication to pub.dev.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev.

# Version and build number for the application.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add dependencies for the project.
dependencies:
  flutter:
    sdk: flutter

  # For iOS-style icons.
  cupertino_icons: ^1.0.8

  # For SQLite database operations.
  sqflite: ^2.4.1

  # For file system paths and storage access.
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended linting rules for Flutter projects.
  flutter_lints: ^5.0.0




# Flutter-specific configurations.
flutter:
  uses-material-design: true

  # Uncomment to add assets to the project.
  assets:
    - assets/images/

  # Uncomment to add custom fonts.
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  #
